export enum Event {
  ReceiveMessage = "ReceiveMessage",
  PlayerJoined = "PlayerJoined",
  PlayerReconnected = "PlayerReconnected",
  PlayerListUpdated = "PlayerListUpdated",
  CreateRoomSuccess = "CreateRoomSuccess",
  JoinRoomSuccess = "JoinRoomSuccess",
  ChangePlayerNameSuccess = "ChangePlayerNameSuccess",
  StartGameSuccess = "StartGameSuccess",
  GetQuestionSuccess = "GetQuestionSuccess",
  NextPlayerSuccess = "NextPlayerSuccess",
  EndGameSuccess = "EndGameSuccess",
  ResetGameSuccess = "ResetGameSuccess",
  LeaveRoomSuccess = "LeaveRoomSuccess",
  ReconnectSuccess = "ReconnectSuccess",
  GameStarted = "GameStarted",
  QuestionAssigned = "QuestionAssigned",
  NextPlayerTurn = "NextPlayerTurn",
  GameEnded = "GameEnded",
  GameReset = "GameReset",
  OperationFailed = "OperationFailed",
  PlayerLeft = "PlayerLeft",

  // Invoke
  CreateRoom = "CreateRoom",
  JoinRoom = "JoinRoom",
  ChangePlayerName = "ChangePlayerName",
  StartGame = "StartGame",
  GetRandomQuestionForRoom = "GetRandomQuestionForRoom",
  NextPlayer = "NextPlayer",
  EndGame = "EndGame",
  ResetGame = "ResetGame",
  LeaveRoom = "LeaveRoom",
  ReconnectPlayer = "ReconnectPlayer",
  SendMessage = "SendMessage",
}
